name: build

on:
  push: {}

  pull_request: {}

  release:
    types: [created]

jobs:
  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pip install black flake8 isort
    - run: isort --version
    - run: black --version
    - run: flake8 --version
    - run: black --check .
    - run: isort --check .
    - run: flake8 .

  deploy:
    if: ${{ github.event_name == 'release' }}

    name: Upload to Pypi
    needs: quality

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Check version
      run: |
        release=${GITHUB_REF#refs/tags/}
        echo "release $release"
        TAG_VERSION=$(echo "${GITHUB_REF##*/}" | sed 's/^v//')
        echo "Tag version: $TAG_VERSION"
        version=$(python setup.py --version)
        echo "$release == $version"
        test "$release" == "$version"

    - name: Build pip package
      run: |
        python setup.py sdist --verbose

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* --verbose
